### PR TITLE
updates for shiny headaches

### PR DESCRIPTION
**Pull request by jread-usgs**
- [x] stop application button
 - [x] use list_sites
 - [x] update/render on click
 - [x] updated to current mda.streams w/ data codes

### CODE REVIEW

**Comment by jread-usgs** [comment]
to do: CI banding, map in lower left corner, checkbox for union vs intersection, extended site names in dropdown.

**Comment by aappling-usgs** [comment]
loving the map autozoom in explore_timeseries!

**Comment by aappling-usgs** [comment]
awesome. truly awesome.

**Comment by jread-usgs** [comment]
awww shucks... :+1:

**Pull request merged**
